"""
Graph Generator — produce PNG graphs from SmokePing RRD data via rrdtool.
"""

import os
import logging
import subprocess
from typing import Optional

from . import APP_NAME, VERSION

log = logging.getLogger("smoke-notifier")


class GraphGenerator:
    """Generate SmokePing-style PNG graphs via rrdtool graph."""

    DURATION_LABELS = {
        "1h":  "Last 1 Hour",
        "3h":  "Last 3 Hours",
        "6h":  "Last 6 Hours",
        "12h": "Last 12 Hours",
        "24h": "Last 24 Hours",
    }

    def __init__(self, config):
        self.config = config
        os.makedirs(config.graph_temp_dir, exist_ok=True)

    def _safe_filename(self, label: str) -> str:
        safe = label.replace(" ", "_").replace("/", "-").replace("(", "").replace(")", "")
        return "".join(c for c in safe if c.isalnum() or c in "_-")

    def generate(self, link_cfg: dict, duration: str = None, baseline: Optional[dict] = None) -> Optional[str]:
        """
        Generate a PNG graph for a link.
        Returns: absolute path to PNG file, or None on failure.
        """
        if not self.config.graph_enabled:
            return None

        duration   = duration or self.config.graph_duration
        rrd_file   = os.path.join(self.config.rrd_base_path, link_cfg["rrd_path"])
        num_probes = link_cfg.get("num_probes", self.config.default_num_probes)
        
        # Use baseline if provided, else fallback to config
        if baseline:
            warn_rtt = baseline.get("warn_rtt", link_cfg.get("warn_rtt", 30))
            crit_rtt = baseline.get("crit_rtt", link_cfg.get("crit_rtt", 80))
        else:
            warn_rtt = link_cfg.get("warn_rtt", 30)
            crit_rtt = link_cfg.get("crit_rtt", 80)

        safe_name = self._safe_filename(link_cfg["label"])
        png_path  = os.path.join(
            self.config.graph_temp_dir, f"{safe_name}_{duration}.png"
        )

        title = (
            f"{link_cfg['label']} — "
            f"{self.DURATION_LABELS.get(duration, duration)}"
        )

        # Build rrdtool graph command
        cmd = [
            "rrdtool", "graph", png_path,
            "--start", f"-{duration}",
            "--end", "now",
            "--width",  str(self.config.graph_width),
            "--height", str(self.config.graph_height),
            "--title",  title,
            "--vertical-label", "RTT (ms)",
            "--slope-mode",
            "--alt-autoscale-max",
            "--lower-limit", "0",
            # Premium Dark Theme (Tokyo Night style)
            "--color", "BACK#1a1b26",
            "--color", "CANVAS#24283b",
            "--color", "FONT#a9b1d6",
            "--color", "GRID#414868",
            "--color", "MGRID#565f89",
            "--color", "AXIS#414868",
            "--color", "ARROW#bb9af7",
            "--font", "DEFAULT:9",
            "--font", "TITLE:11:Bold",
            "--border", "0",
            # Data definitions
            f"DEF:median_raw={rrd_file}:median:AVERAGE",
            f"DEF:loss_raw={rrd_file}:loss:AVERAGE",
            # Convert median from seconds to ms
            "CDEF:median_ms=median_raw,1000,*",
            # Convert loss from packet count to percentage
            f"CDEF:loss_pct=loss_raw,{num_probes},/,100,*",
            # Plot loss as soft red transparent area
            "AREA:loss_pct#f7768e70:Loss (%)   ",
            # Plot RTT as teal line with shadow effect (thick line)
            "LINE2:median_ms#73daca:RTT median (ms)\\n",
            # Threshold lines
            f"HRULE:{warn_rtt}#e0af68:Warning  ({warn_rtt}ms):dashes=5,3",
            f"HRULE:{crit_rtt}#db4b4b:Critical ({crit_rtt}ms)\\n:dashes=5,3",
            # Statistics with cleaner spacing
            "GPRINT:median_ms:LAST:Current\\: %6.2lf ms",
            "GPRINT:median_ms:AVERAGE:Avg\\: %6.2lf ms",
            "GPRINT:median_ms:MAX:Max\\: %6.2lf ms\\n",
            "GPRINT:loss_pct:LAST:Loss now\\: %5.1lf %%   ",
            "GPRINT:loss_pct:AVERAGE:Avg loss\\: %5.1lf %%\\n",
            "COMMENT: \\n",
            f"COMMENT:  Generated by {APP_NAME} v{VERSION}  (Auto-Baseline\\: {'ON' if baseline else 'OFF'})\\r",
        ]

        try:
            result = subprocess.run(
                cmd, capture_output=True, text=True, timeout=15
            )
            if result.returncode != 0:
                log.error(f"rrdtool graph error: {result.stderr.strip()}")
                return None

            if os.path.isfile(png_path):
                log.debug(f"Graph generated: {png_path}")
                return png_path

            log.warning(f"Graph file not created: {png_path}")
            return None

        except FileNotFoundError:
            log.error("rrdtool binary not found for graph generation")
            return None
        except subprocess.TimeoutExpired:
            log.error("rrdtool graph timed out")
            return None
        except Exception as e:
            log.error(f"Graph generation failed: {e}")
            return None

    def cleanup(self, png_path: str):
        """Remove temporary PNG after sending."""
        try:
            if png_path and os.path.isfile(png_path):
                os.remove(png_path)
        except OSError:
            pass
